# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  
  # Ubuntu 18.04
  #config.vm.box = "ubuntu/bionic64"

  # CentOS
  config.vm.box = "centos/8"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
  end

  # Multi-Machine Definition
  # Vagrant is able to define and control multiple guest machines per Vagrantfile. 
  # This is known as a "multi-machine" environment. These machines are generally 
  # able to work together or are somehow associated with each other. 

  config.vm.define "master" do |master|
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    master.vm.network "private_network", ip: "10.0.0.2"
  end

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "10.0.0.3"
  end

end
